# Ansible playbook to add basic Netconf configuration on Cisco IOSXE devices
---
- name: Add basic netconf config to hosts
  hosts: lab-switches
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Add NETCONF configuration to hosts
      cisco.ios.ios_config:
        lines:
          - ip http server
          - ip http authentication local
          - ip http secure-server
          - ip http client source-interface GigabitEthernet0/0
          - netconf-yang
          - netconf ssh
        save_when: modified
      register: print_output

    - name: Print the Netconf configuration output to screen
      ansible.builtin.debug:
        var: print_output
...
