# Playbook to gather serial numbers from Cisco devices using ansible-netconf
# Playbook will save the serial numbers to a CSV file in a folder called output

- name: Retrieve serial numbers using Netconf
  hosts: CSR_hosts
  gather_facts: false
  connection: netconf

  tasks:
    - name: "Task1: Retrieve Serial Number"
      ansible.netcommon.netconf_get:
        filter: <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native"><hardware><id></id></hardware></native>
      register: serial_numbers

    - name: "Task2: Generate Timestamp"
      ansible.builtin.command: date +"%Y-%m-%d_%H-%M-%S"
      register: timestamp
      changed_when: false

    - name: "TASK 3: Ensure outputs/ folder exists"
      file:
        path: "outputs"
        state: directory
      run_once: true

    - name: "Task4: Store Output in CSV File"
      copy:
        content: |
          Hostname,Serial Number
          {{ inventory_hostname }},{{ serial_numbers.stdout_lines[0] }}
        dest: "outputs/serial_numbers_{{ timestamp.stdout }}.csv"
        mode: '0644'
...
