# Playbook using Netconf to get running config from host
---
- name: Get the running configuration using Netconf
  hosts: CSR-1
  gather_facts: false
  connection: netconf

  tasks:
    - name: "Print Running Config"
      ansible.netcommon.netconf_get:
        source: running
        display: "native" #Can be displayed as xml, json, pretty(similar to xml) or native
      register: config_output

    - name: "Print the config to screen"
      ansible.builtin.debug:
        var: config_output["output"] #adding ["output"] ensures only the configuration is displayed
...
