---
# Playbook to backup configs using Netconf
- name: Add basic netconf config to hosts
  hosts: CSR_hosts
  gather_facts: false
  connection: netconf

  tasks:
    - name: "Task1: Create a backup folder"
      file:
        path: "backups"
        state: directory
      run_once: true

    - name: "Task2: Backup device configuration and save to backup folder"
      ansible.netcommon.netconf_config:
        backup: true
        backup_options:
          filename: backups_{{ inventory_hostname }}.cfg
...
